version: "3.8"
services:
  productos:
    build: ../productos
    ports:
      - "2001:2001"
    networks:
      - microservices-network
  clientes:
    build: ../clientes
    ports:
      - "2000:2000"
    networks:
      - microservices-network
  ventas:
    build: ../ventas
    ports:
      - "2002:2002"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
